Atividade 4 Estados

In [1]:
from pathlib import Path
import pandas as pd


PASTA_PROJETO = Path.cwd()3

ARQUIVO_EXCEL = r"H:\python\atividades\GitNovo\AtividadeEstado\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

ARQUIVO_ESTADOS = r"H:\python\atividades\GitNovo\AtividadeEstado\populacao_por_estado_2010_2022.csv"

ARQUIVO_MUNICIPIOS = r"H:\python\atividades\GitNovo\AtividadeEstado\populacao_por_municipio_2010_2022.csv"

print("Pasta do projeto:", PASTA_PROJETO)
print("Arquivo Excel:", ARQUIVO_EXCEL)

Pasta do projeto: /mnt/data/AtividadeEstado_work/AtividadeEstado
Arquivo Excel: /mnt/data/AtividadeEstado_work/AtividadeEstado/CD2022_Populacao_2010_Compatibilizada_20231222.xlsx

In [2]:

df = pd.read_excel(ARQUIVO_EXCEL, sheet_name="Municípios", header=2)


df = df.dropna(subset=["UF", "NOME DO MUNICÍPIO"]).copy()


colunas_populacao = [
    "População Município 2010\n(Sinopse)",
    "População 2010 (Alterações de Limites até 2022)1",
    "População Censo 2022",
]

for coluna in colunas_populacao:
    df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

df.head()

   Unnamed: 0  ... População Censo 2022
0         NaN  ...              21494.0
1         NaN  ...              96833.0
2         NaN  ...               5351.0
3         NaN  ...              86887.0
4         NaN  ...              15890.0

[5 rows x 8 columns]

## População agregada por estado

In [3]:

populacao_estado = (
    df.groupby("UF")[
        [
            "População 2010 (Alterações de Limites até 2022)1",
            "População Censo 2022",
        ]
    ]
    .sum()
    .reset_index()
)

populacao_estado["Crescimento_2010_2022"] = (
    populacao_estado["População Censo 2022"]
    - populacao_estado["População 2010 (Alterações de Limites até 2022)1"]
)

populacao_estado = populacao_estado.sort_values(
    "Crescimento_2010_2022", ascending=False
).reset_index(drop=True)

populacao_estado

    UF  ...  Crescimento_2010_2022
0   SP  ...              3149039.0
1   SC  ...              1361925.0
2   GO  ...              1054706.0
3   PR  ...               999854.0
4   MG  ...               942659.0
5   MT  ...               623527.0
6   PA  ...               539080.0
7   AM  ...               457628.0
8   CE  ...               343313.0
9   ES  ...               318760.0
10  MS  ...               307989.0
11  PE  ...               262876.0
12  DF  ...               245222.0
13  PB  ...               208159.0
14  MA  ...               201910.0
15  RS  ...               189036.0
16  RR  ...               186228.0
17  PI  ...               152102.0
18  SE  ...               142152.0
19  RN  ...               134702.0
20  TO  ...               128015.0
21  BA  ...               124555.0
22  AC  ...                96459.0
23  RJ  ...                65245.0
24  AP  ...                64233.0
25  RO  ...                18787.0
26  AL  ...                 6796.0

[27 rows x 4 columns]

In [4]:

populacao_estado.to_csv(
    ARQUIVO_ESTADOS,
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print(f"Arquivo salvo em: {ARQUIVO_ESTADOS}")

Arquivo salvo em: /mnt/data/AtividadeEstado_work/AtividadeEstado/populacao_por_estado_2010_2022.csv

## População por município

In [5]:


populacao_municipio = df[
    [
        "UF",
        "COD. UF",
        "COD. MUNIC",
        "NOME DO MUNICÍPIO",
        "População 2010 (Alterações de Limites até 2022)1",
        "População Censo 2022",
    ]
].copy()

populacao_municipio["Crescimento_2010_2022"] = (
    populacao_municipio["População Censo 2022"]
    - populacao_municipio["População 2010 (Alterações de Limites até 2022)1"]
)

populacao_municipio = populacao_municipio.sort_values(
    "Crescimento_2010_2022", ascending=False
).reset_index(drop=True)

populacao_municipio.head(20)

    UF  COD. UF  ...  População Censo 2022 Crescimento_2010_2022
0   AM     13.0  ...             2063689.0              261675.0
1   DF     53.0  ...             2817381.0              245222.0
2   SP     35.0  ...            11451999.0              198496.0
3   SP     35.0  ...              723682.0              136866.0
4   GO     52.0  ...             1437366.0              135454.0
5   RR     14.0  ...              413486.0              129173.0
6   SC     42.0  ...              537211.0              115971.0
7   PA     15.0  ...              267836.0              113928.0
8   MS     50.0  ...              898100.0              111326.0
9   PB     25.0  ...              833932.0              110417.0
10  MG     31.0  ...              713224.0              109211.0
11  ES     32.0  ...              520653.0              103323.0
12  SC     42.0  ...              616317.0              101029.0
13  MT     51.0  ...              650877.0               97675.0
14  SP     35.0  ...              698642.0               93960.0
15  PE     26.0  ...              386791.0               92829.0
16  SP     35.0  ...              349935.0               87884.0
17  SC     42.0  ...              222598.0               85264.0
18  MT     51.0  ...              196312.0               83213.0
19  MA     21.0  ...              244579.0               82642.0

[20 rows x 7 columns]

In [6]:

populacao_municipio.to_csv(
    ARQUIVO_MUNICIPIOS,
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print(f"Arquivo salvo em: {ARQUIVO_MUNICIPIOS}")

Arquivo salvo em: /mnt/data/AtividadeEstado_work/AtividadeEstado/populacao_por_municipio_2010_2022.csv

In [7]:

print("Arquivos gerados:")
for arquivo in [ARQUIVO_ESTADOS, ARQUIVO_MUNICIPIOS]:
    print(f"- {arquivo.name}: {arquivo.stat().st_size} bytes")

print("\n5 estados com maior crescimento absoluto:")
display(populacao_estado.head(5))

print("\n10 municípios com maior crescimento absoluto:")
display(populacao_municipio.head(10))

Arquivos gerados:
- populacao_por_estado_2010_2022.csv: 972 bytes
- populacao_por_municipio_2010_2022.csv: 281661 bytes

5 estados com maior crescimento absoluto:

   UF  ...  Crescimento_2010_2022
0  SP  ...              3149039.0
1  SC  ...              1361925.0
2  GO  ...              1054706.0
3  PR  ...               999854.0
4  MG  ...               942659.0

[5 rows x 4 columns]

10 municípios com maior crescimento absoluto:

   UF  COD. UF  ...  População Censo 2022 Crescimento_2010_2022
0  AM     13.0  ...             2063689.0              261675.0
1  DF     53.0  ...             2817381.0              245222.0
2  SP     35.0  ...            11451999.0              198496.0
3  SP     35.0  ...              723682.0              136866.0
4  GO     52.0  ...             1437366.0              135454.0
5  RR     14.0  ...              413486.0              129173.0
6  SC     42.0  ...              537211.0              115971.0
7  PA     15.0  ...              267836.0              113928.0
8  MS     50.0  ...              898100.0              111326.0
9  PB     25.0  ...              833932.0              110417.0

[10 rows x 7 columns]