# Aula — Tabelas 5 + Tabela 1.1.1

In [1]:
import pandas as pd


arquivo_2012 = "Tabela5-sem_emprego_2012.csv"
arquivo_2026 = "Tabela5-sem_emprego_2026.csv"
arquivo_horas = "Tabela 1.1.1.xls"


t2012 = pd.read_csv(arquivo_2012, sep=";", encoding="utf-8-sig")
t2026 = pd.read_csv(arquivo_2026, sep=";", encoding="utf-8-sig")


display(t2012.head())
display(t2026.head())

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,"45,3","54,7"
1,AL,27,Alagoas,"44,7","55,3"
2,AM,13,Amazonas,"47,5","52,5"
3,AP,16,Amapá,"48,1","51,9"
4,BA,29,Bahia,"43,8","56,2"

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,"53,2","46,8"
1,AL,27,Alagoas,"50,7","49,3"
2,AM,13,Amazonas,"46,8","53,2"
3,AP,16,Amapá,"51,1","48,9"
4,BA,29,Bahia,"44,7","55,3"

In [2]:

comp = t2012.merge(
    t2026,
    on=["Sigla", "Código", "Estado"],
    how="inner"
)

comp.head()

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,"45,3","54,7","53,2","46,8"
1,AL,27,Alagoas,"44,7","55,3","50,7","49,3"
2,AM,13,Amazonas,"47,5","52,5","46,8","53,2"
3,AP,16,Amapá,"48,1","51,9","51,1","48,9"
4,BA,29,Bahia,"43,8","56,2","44,7","55,3"

In [13]:

tabela_horas = pd.read_excel(
    arquivo_horas,
    sheet_name="2022",
    header=None
)

tabela_horas.head(10)

,0,1,2,3,4,5,6,7
0,Tabela 1.1.1 - Número médio de horas semanais ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Grandes Regiões e Unidades da Federação,Número médio de horas semanais dedicadas aos c...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Total,Por sexo e cor ou raça,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Total,NaN,Homem,NaN,Mulher,NaN
7,NaN,NaN,Branca,Preta ou parda,Branca,Preta ou parda,Branca,Preta ou parda
8,Brasil,16.985781,16.54593,17.333142,11.705136,11.74633,20.404106,22.037998
9,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.29578,20.534188

In [14]:


horas = tabela_horas.iloc[8:, [0, 1]].copy()
horas.columns = ["Estado", "Horas_semanais_total"]


estados = comp["Estado"].tolist()
horas = horas[horas["Estado"].isin(estados)].copy()


horas["Horas_semanais_total"] = pd.to_numeric(
    horas["Horas_semanais_total"],
    errors="coerce"
)

horas.head()

      Estado  Horas_semanais_total
10  Rondônia             17.014162
11      Acre             13.606903
12  Amazonas             16.807290
13   Roraima             13.639257
14      Pará             16.474268

In [15]:

cruzado = comp.merge(
    horas,
    on="Estado",
    how="inner"
)

cruzado.head()

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Horas_semanais_total
0,AC,12,Acre,"45,3","54,7","53,2","46,8",13.606903
1,AL,27,Alagoas,"44,7","55,3","50,7","49,3",20.217129
2,AM,13,Amazonas,"47,5","52,5","46,8","53,2",16.807290
3,AP,16,Amapá,"48,1","51,9","51,1","48,9",13.586656
4,BA,29,Bahia,"43,8","56,2","44,7","55,3",17.849776

In [16]:

colunas_numericas = [
    "Desocupados - homens (2012 T1)",
    "Desocupados - mulheres (2012 T1)",
    "Desocupados - homens (2026 T1)",
    "Desocupados - mulheres (2026 T1)"
]

for coluna in colunas_numericas:
    cruzado[coluna] = (
        cruzado[coluna]
        .astype(str)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

cruzado["Diferença homens 2026-2012"] = (
    cruzado["Desocupados - homens (2026 T1)"]
    - cruzado["Desocupados - homens (2012 T1)"]
)

cruzado["Diferença mulheres 2026-2012"] = (
    cruzado["Desocupados - mulheres (2026 T1)"]
    - cruzado["Desocupados - mulheres (2012 T1)"]
)


cruzado["Diferença mulheres-homens 2012"] = (
    cruzado["Desocupados - mulheres (2012 T1)"]
    - cruzado["Desocupados - homens (2012 T1)"]
)

cruzado["Diferença mulheres-homens 2026"] = (
    cruzado["Desocupados - mulheres (2026 T1)"]
    - cruzado["Desocupados - homens (2026 T1)"]
)

cruzado

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Horas_semanais_total,Diferença homens 2026-2012,Diferença mulheres 2026-2012,Diferença mulheres-homens 2012,Diferença mulheres-homens 2026
0,AC,12,Acre,45.3,54.7,53.2,46.8,13.606903,7.9,-7.9,9.4,-6.4
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,20.217129,6.0,-6.0,10.6,-1.4
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,16.807290,-0.7,0.7,5.0,6.4
3,AP,16,Amapá,48.1,51.9,51.1,48.9,13.586656,3.0,-3.0,3.8,-2.2
4,BA,29,Bahia,43.8,56.2,44.7,55.3,17.849776,0.9,-0.9,12.4,10.6
5,CE,23,Ceará,51.1,48.9,52.7,47.3,19.499293,1.6,-1.6,-2.2,-5.4
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,15.096351,6.9,-6.9,18.0,4.2
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,17.111106,1.1,-1.1,7.2,5.0
8,GO,52,Goiás,41.0,59.0,47.5,52.5,15.186471,6.5,-6.5,18.0,5.0
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,16.669614,1.9,-1.9,5.6,1.8
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,17.502141,5.5,-5.5,13.8,2.8
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,15.309783,-1.9,1.9,5.6,9.4
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,14.239989,-1.3,1.3,11.8,14.4
13,PA,15,Pará,43.2,56.8,48.3,51.7,16.474268,5.1,-5.1,13.6,3.4
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,18.920816,4.5,-4.5,11.2,2.2
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,19.306249,4.8,-4.8,12.2,2.6
16,PI,22,Piauí,51.2,48.8,55.1,44.9,17.960366,3.9,-3.9,-2.4,-10.2
17,PR,41,Paraná,40.3,59.7,46.3,53.7,15.390122,6.0,-6.0,19.4,7.4
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,16.716263,1.2,-1.2,11.6,9.2
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,18.307740,-2.8,2.8,-2.0,3.6
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,17.014162,-10.4,10.4,13.2,34.0
21,RR,14,Roraima,41.8,58.2,43.4,56.6,13.639257,1.6,-1.6,16.4,13.2
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,15.356709,4.6,-4.6,14.4,5.2
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,16.039355,1.9,-1.9,14.6,10.8
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,18.826541,-6.2,6.2,7.0,19.4
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,17.071295,0.8,-0.8,9.2,7.6
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,15.815781,-9.1,9.1,-10.6,7.6

In [17]:

cruzado = cruzado[
    [
        "Sigla",
        "Código",
        "Estado",
        "Desocupados - homens (2012 T1)",
        "Desocupados - mulheres (2012 T1)",
        "Desocupados - homens (2026 T1)",
        "Desocupados - mulheres (2026 T1)",
        "Diferença homens 2026-2012",
        "Diferença mulheres 2026-2012",
        "Diferença mulheres-homens 2012",
        "Diferença mulheres-homens 2026",
        "Horas_semanais_total"
    ]
]

cruzado

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Diferença homens 2026-2012,Diferença mulheres 2026-2012,Diferença mulheres-homens 2012,Diferença mulheres-homens 2026,Horas_semanais_total
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9,9.4,-6.4,13.606903
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0,10.6,-1.4,20.217129
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7,5.0,6.4,16.807290
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0,3.8,-2.2,13.586656
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9,12.4,10.6,17.849776
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6,-2.2,-5.4,19.499293
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9,18.0,4.2,15.096351
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1,7.2,5.0,17.111106
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5,18.0,5.0,15.186471
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9,5.6,1.8,16.669614
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5,13.8,2.8,17.502141
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9,5.6,9.4,15.309783
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3,11.8,14.4,14.239989
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1,13.6,3.4,16.474268
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5,11.2,2.2,18.920816
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8,12.2,2.6,19.306249
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9,-2.4,-10.2,17.960366
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0,19.4,7.4,15.390122
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2,11.6,9.2,16.716263
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8,-2.0,3.6,18.307740
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4,13.2,34.0,17.014162
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6,16.4,13.2,13.639257
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6,14.4,5.2,15.356709
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9,14.6,10.8,16.039355
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2,7.0,19.4,18.826541
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8,9.2,7.6,17.071295
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1,-10.6,7.6,15.815781

In [18]:


cruzado.to_csv(
    "geral.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

cruzado.to_excel(
    "geral.xlsx",
    index=False
)

print("Arquivos salvos: geral.csv e geral.xlsx")

Arquivos salvos: geral.csv e geral.xlsx

In [19]:


cruzado.sort_values(
    "Diferença mulheres-homens 2026",
    ascending=False
).head(10)

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),Diferença homens 2026-2012,Diferença mulheres 2026-2012,Diferença mulheres-homens 2012,Diferença mulheres-homens 2026,Horas_semanais_total
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4,13.2,34.0,17.014162
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2,7.0,19.4,18.826541
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3,11.8,14.4,14.239989
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6,16.4,13.2,13.639257
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9,14.6,10.8,16.039355
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9,12.4,10.6,17.849776
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9,5.6,9.4,15.309783
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2,11.6,9.2,16.716263
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8,9.2,7.6,17.071295
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1,-10.6,7.6,15.815781